#!/bin/bash

apt-get -qq update
apt-get -y --force-yes install \
  build-essential \
  wget \
  libtool \
  zlib1g-dev \
  libssl-dev \
  libreadline6-dev \
  libyaml-dev \
  ncurses-dev \
  libgdbm-dev \
  libpq-dev \
  libffi-dev

cd /usr/local/src
wget --quiet ftp://ftp.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
tar xzf ruby-2.1.1.tar.gz
cd /usr/local/src/ruby-2.1.1
./configure --prefix=/usr/local/ruby
make
make install
rm /usr/local/src/ruby-2.1.1.tar.gz

cat << 'EOF' > ~/.gemrc
---
:update_sources: true
:benchmark: false
:backtrace: true
:verbose: true
gem: --no-ri --no-rdoc
install: --no-rdoc --no-ri
update:  --no-rdoc --no-ri
EOF

/usr/local/ruby/bin/gem install bundler
